import type { Metadata } from 'next';
import { NextAuthProvider } from '@/src/providers/AuthProvider';
import { authOptions } from '@/config/auth';
import { getServerSession } from 'next-auth';
import PrivateRoute from '@/src/routing/PrivateRoute';
import React from 'react';
import { LoadingErrorProvider } from '@/src/context/loadingErrorContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <NextAuthProvider session={session}>
      <LoadingErrorProvider>
        <PrivateRoute rejected={false} isPublic={false} session={session}>
          {children}
        </PrivateRoute>
      </LoadingErrorProvider >
    </NextAuthProvider>
  );
}
