
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@mui/material/styles/ThemeProvider";
import createTheme from "@mui/material/styles/createTheme";

const inter = Inter({ subsets: ["latin"] });

const theme = createTheme({
  palette: {
    mode: 'dark',  // Habilita el modo oscuro
    // Otros colores personalizados para modo oscuro si es necesario
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    <html lang="en">
     
      <body className={inter.className}>
      {children}
      
       
      </body>
      
    </html>
  );
}
